name: practical_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #B
  build_runner: ^2.4.5

  #D
  dio: ^5.2.1+1

  #E
  equatable: ^2.0.5

  #G
  google_fonts: ^5.1.0

  #H
  http_mock_adapter: ^0.4.4

  #I
  infinite_scroll_pagination: ^3.2.0

  #M
  mockito: ^5.4.2

  #P
  provider: ^6.0.5

  #S
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
